#!/usr/bin/env ruby

PID=ARGV[0]
if not PID
    $stderr.puts "#$0 PID"
    exit
end

# The signal handler only takes effects before running "exec"
Signal.trap('INT') do
    $stderr.puts "trace cancled"
    `./ctrl #{PID} 0`
    exit
end

if not File.exists? "/proc/#{PID}"
    $stderr.puts "process #{PID} does not exist"
    exit
end

`./ctrl #{PID} 1`

$stderr.puts "waiting to attach to #{PID}"
path = "/tmp/phptrace.trace.#{PID}"
until File.exists? path
    sleep 0.2
end
$stderr.puts "attached"

childpid = fork {exec "./tracedump #{path}"}
Process.wait childpid
`./ctrl #{PID} 0`
